blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('blogs/', views.blogs, name='blogs'),
    path('blog/<str:pk>/', views.blog, name='blog'),

    path('exhibitions/', views.exhibitions, name='exhibitions'),

    path('create-blog/', views.createBlog, name='create-blog'),
    path('update-blog/<str:pk>/', views.updateBlog, name='update-blog'),
    path('delete-blog/<str:pk>/', views.deleteBlog, name='delete-blog'),

    path('create-exhibition/', views.createExhibition, name='create-exhibition'),
    path('update-exhibition/<str:pk>/', views.updateExhibition, name='update-exhibition'),
    path('delete-exhibition/<str:pk>/', views.deleteExhibition, name='delete-exhibition'),
]

farmec/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.home, name='home'),

    path('admin/', admin.site.urls),

    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),

    path('home/', include('home.urls')),
    path('about/', include('about.urls')),
    path('suppliers/', include('suppliers.urls')),
    path('blog/', include('blog.urls')),
    path('spareparts/', include('spareparts.urls')),
    path('stripepayments/', include('stripepayments.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

spareparts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('spare-parts/', views.spareparts, name='spare-parts'),
    path('parts-page/<str:pk>/', views.partspage, name='parts-page'),

    path('warranty-claims/', views.warrantyclaims, name='warranty-claims'),
    path('single-warranty/<str:pk>/', views.singlewarranty, name='single-warranty'),
    path('create-warranty/', views.createWarranty, name='create-warranty'),
    path('update-warranty/<str:pk>/', views.updateWarranty, name='update-warranty'),
    path('delete-warranty/<str:pk>/', views.deleteWarranty, name='delete-warranty'),

    path('machine-registration/', views.machinereg, name='machine-registration'),
    path('regsingle/<str:pk>/', views.regsingle, name='regsingle'),
    path('create-registration/', views.createRegistration, name='create-registration'),
    path('update-registration/<str:pk>/', views.updateRegistration, name='update-registration'),
    path('delete-registration/<str:pk>/', views.deleteRegistration, name='delete-registration'),

    path('create-supplier-page/', views.createPageform, name='create-supplier-page'),
    path('update-supplier-page/<str:pk>/', views.updatePageform, name='update-supplier-page'),
    path('delete-supplier-page/<str:pk>/', views.deletePageform, name='delete-supplier-page'),

    path('create-parts-page/', views.createPartsform, name='create-parts-page'),
    path('update-parts-page/<str:pk>/', views.updatePartsform, name='update-parts-page'),
    path('delete-parts-page/<str:pk>/', views.deletePartsform, name='delete-parts-page'),

    path('generate-reg/<str:pk>/', views.generate_reg, name='generate-reg'),
    path('generate-claim/<str:pk>/', views.generate_claim, name='generate-claim'),
]

spareparts/models.py
from django.db import models
import uuid

# Create your models here.
class SupplierPage(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    logo_image = models.ImageField(null=True, blank=True, upload_to='models/', default="default.jpg")
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ['created']

    @property
    def imageurl(self):
        try:
            url = self.logo_image.url
        except: 
            url = ''
        return url

class PartsPage(models.Model):
    supplier = models.ForeignKey(SupplierPage, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    catalogue_link = models.URLField(max_length=200, blank=True, null=True)
    supplier_page = models.URLField(max_length=200, blank=True, null=True)
    marketing_image = models.ImageField(null=True, blank=True, upload_to='models/', default="default.jpg")
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ['created']

    @property
    def imageurl(self):
        try:
            url = self.marketing_image.url
        except: 
            url = ''
        return url

class WarrantyClaim(models.Model):
    dealer = models.CharField(max_length=200, blank=True, null=True)
    dealer_contact = models.CharField(max_length=200, blank=True, null=True)
    owner_name = models.CharField(max_length=200, blank=True, null=True, verbose_name="Owner Name")
    machine_model = models.CharField(max_length=200, blank=True, null=True)
    serial_number = models.CharField(max_length=200, blank=True, null=True)
    install_date = models.CharField(max_length=200, blank=True, null=True)
    failure_date = models.CharField(max_length=200, blank=True, null=True)
    repair_date = models.CharField(max_length=200, blank=True, null=True)
    failure_details = models.TextField(blank=True, null=True)
    repair_details = models.TextField(blank=True, null=True)
    labour_hours = models.CharField(max_length=200, blank=True, null=True)
    completed_by = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        if self.owner_name and self.dealer:
            return str(self.owner_name + "-" + self.dealer)
        else:
            return str(self.id)

    class Meta:
        ordering = ['-created']

class PartsRequired(models.Model):
    warranty = models.ForeignKey(WarrantyClaim, on_delete=models.CASCADE, null=True, blank=True)
    part_number = models.CharField(max_length=200, blank=True, null=True)
    quantity_needed = models.CharField(max_length=20, blank=True, null=True, default=1)
    invoice_number = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

class MachineRegistration(models.Model):
    dealer_name = models.CharField(max_length=200, blank=True, null=True, verbose_name="Dealer Name")
    dealer_address = models.CharField(max_length=200, blank=True, null=True)
    owner_name = models.CharField(max_length=200, blank=True, null=True)
    owner_address = models.CharField(max_length=200, blank=True, null=True)
    machine_model = models.CharField(max_length=200, blank=True, null=True)
    serial_number = models.CharField(max_length=200, blank=True, null=True)
    install_date = models.CharField(max_length=200, blank=True, null=True)
    invoice_number = models.CharField(max_length=200, blank=True, null=True)
    complete_supply = models.BooleanField(default=False, blank=True, null=True)
    pdi_complete = models.BooleanField(default=False, blank=True, null=True)
    pto_correct = models.BooleanField(default=False, blank=True, null=True)
    machine_test_run = models.BooleanField(default=False, blank=True, null=True)
    safety_induction = models.BooleanField(default=False, blank=True, null=True)
    operator_handbook = models.BooleanField(default=False, blank=True, null=True)
    date = models.CharField(max_length=200, blank=True, null=True)
    completed_by = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.owner_name)

    class Meta:
        ordering = ['-created']
    

spareparts/forms.py
from django.db.models.base import Model
from django import forms
from django.forms import ModelForm, widgets, forms, formsets
from . models import WarrantyClaim, MachineRegistration, SupplierPage, PartsPage
from . models import PartsRequired

class WarrantyClaimForm(ModelForm):
    class Meta:
        model = WarrantyClaim
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(WarrantyClaimForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

class PartsRequiredForm(ModelForm):
    class Meta:
        model = PartsRequired
        # fields = '__all__'
        exclude = ['warranty', 'id']

    def __init__(self, *args, **kwargs):
        super(PartsRequiredForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

class SupplierPageForm(ModelForm):
    class Meta:
        model = SupplierPage
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(SupplierPageForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

class PartsPageForm(ModelForm):
    class Meta:
        model = PartsPage
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PartsPageForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

class MachineRegistrationForm(ModelForm):
    class Meta:
        model = MachineRegistration
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(MachineRegistrationForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})


    

spareparts/templates/spareparts/claim_single.html
{% extends 'main.html' %}

{% block content %}

<section id="warranty-machine-single">
    <h2 class="text-center">Warranty Claim Form <div class="bottom-line"></div>
    </h2>
    <button class="btn-nav form-buttons">
        <a href="{% url 'generate-claim' singlewarranty.id %}" class="btn btn-primary">Download PDF</a>
    </button>
    <h1 class="text-center">{{singlewarranty.owner_name}}</h1>
    <div class="single-grid">
        <h1>Dealer Name: </h1>
        <p>{{singlewarranty.dealer}}</p>

        <h1>Dealer Contact: </h1>
        <p>{{singlewarranty.dealer_contact}}</p>

        <h1>Owner Name: </h1>
        <p>{{singlewarranty.owner_name}}</p>

        <h1>Machine Model: </h1>
        <p>{{singlewarranty.machine_model}}</p>

        <h1>Serial Number: </h1>
        <p>{{singlewarranty.serial_number}}</p>

        <h1>Install Date: </h1>
        <p>{{singlewarranty.install_date}}</p>

        <h1>Failure Date: </h1>
        <p>{{singlewarranty.failure_date}}</p>

        <h1>Repair Date: </h1>
        <p>{{singlewarranty.repair_date}}</p>

        <h1>Failure_details: </h1>
        <p>{{singlewarranty.failure_details}}</p>

        <h1>Repair Details: </h1>
        <p>{{singlewarranty.repair_details}}</p>

        <h1>Labour Hours:</h1>
        <p>{{singlewarranty.labour_hours}}</p>
    </div>

    <div class="parts-required-table">
        <h1>Parts Required <div class="bottom-line"></div>
        </h1>
        <table>
            <thead>
                <tr>
                    <th>Part Number</th>
                    <th>Quantity Needed</th>
                    <th>Invoice Number</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                {% for partsrequired in singlewarranty.partsrequired_set.all %}
                <tr>
                    <td>{{ partsrequired.part_number }}</td>
                    <td>{{ partsrequired.quantity_needed }}</td>
                    <td>{{ partsrequired.invoice_number }}</td>
                    <td>{{ partsrequired.description }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% if request.user.is_superuser %}
    <div class="form-buttons btn-nav">
        <a class="btn-small btn-secondary form-button" href="{% url 'update-warranty' pk=singlewarranty.pk %}"><i
                class="fa-solid fa-user-pen"></i>
        </a>
        <a class="btn-small btn-secondary form-button" href="{% url 'delete-warranty' pk=singlewarranty.pk %}"><i
                class="fa-solid fa-trash"></i>
        </a>
    </div>
    {% endif %}
</section>

{% endblock content %}

spareparts/templates/spareparts/machine_registrations.html
{% extends 'main.html' %}

{% block content %}

<section id="warranty-machine">
    <div class="index">
        <h1 class="index-heading">Index:
            <div class="bottom-line-side"></div>
        </h1>
        {% for machinereg in machinereg %}
        <h1 class="index-name"><a class="index-link" href="#form-registration-{{forloop.counter}}">{{forloop.counter}}
                . {{machinereg.owner_name}}</a></h1>
        {% endfor %}
    </div>
    {% for machinereg in machinereg %}
    <div class="warranty-machine-grid" id="form-registration-{{forloop.counter}}">
        <h1>{{forloop.counter}} . {{machinereg.owner_name}} -- {{machinereg.dealer_name}}</h1>
        <button class="btn-nav form-button">
            <a class="btn-small btn-primary" href="{% url 'regsingle' pk=machinereg.pk %}">View Form
                <i class="fa-sharp fa-solid fa-right-to-bracket"></i></a>
        </button>
    </div>
    {% endfor %}
</section>

{% endblock content %}

spareparts/templates/spareparts/page_form.html
{% extends 'main.html' %}

{% block content %}
<h2 class="form-heading text-center">
    {% if request.resolver_match.url_name == 'create-registration' %}
    Machine Registration Form <div class="bottom-line"></div>
    {% elif request.resolver_match.url_name == 'update-registration' %}
    Machine Registration Form <div class="bottom-line"></div>

    {% elif request.resolver_match.url_name == 'create-supplier-page' %}
    Supplier Page Form <div class="bottom-line"></div>
    {% elif request.resolver_match.url_name == 'update-supplier-page' %}
    Supplier Page Form <div class="bottom-line"></div>

    {% elif request.resolver_match.url_name == 'create-parts-page' %}
    Parts Page From <div class="bottom-line"></div>
    {% elif request.resolver_match.url_name == 'update-parts-page' %}
    Parts Page Form <div class="bottom-line"></div>

    {% else %}
    Form <div class="bottom-line"></div>
    {% endif %}
</h2>
<p class="form-lead text-center">Fill out the form field(s) below:</p>


<section id="form">
    <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
        </ul>
        {% endif %}
        {% for field in form %}
        <div class="input">
            <h1>{{field.label}}:</h1>
            <p>{{field}}</p>
        </div>
        {% endfor %}
        <input class="submit btn btn-primary" type="submit"></input>
    </form>
</section>

{% endblock content %}

spareparts/templates/spareparts/parts-page.html
{% extends 'main.html' %}

{% block content %}
<section id="parts-page">

    {% if request.user.is_superuser %}
    <button class="btn-nav">
        <a class="btn btn-secondary" href="{% url 'create-parts-page' %}">Create Catalogue
            <i class="fa-sharp fa-solid fa-right-to-bracket"></i></a>
    </button>
    {% endif %}

    <div class="index">
        <h1 class="index-heading">Index:
            <div class="bottom-line-side"></div>
        </h1>
        {% for partspage in supplierpage.partspage_set.all %}
        <h1 class="index-name"><a class="index-link" href="#machinery-card-{{forloop.counter}}">{{forloop.counter}}
                . {{partspage.name}}</a></h1>
        {% endfor %}
    </div>

    {% for partspage in supplierpage.partspage_set.all %}
    <div class="machinery-card" id="machinery-card-{{forloop.counter}}">
        <div class="machinery-card-link">
            <h1>{{partspage.supplier}}</h1>
            <h1>{{partspage.name}} <div class="bottom-line"></div>
            </h1>
            <button class="supplier-link btn-nav">
                {% if partspage.catalogue_link %}
                <a href="{{partspage.catalogue_link}}" class="btn btn-primary" target="_blank">
                    Catalogue Link
                    <i class="fa-sharp fa-solid fa-right-to-bracket"></i>
                </a>
                {% else %}
                <a href="{{partspage.supplier_page}}" class="btn btn-primary" target="_blank">
                    Catalogue Link
                    <i class="fa-sharp fa-solid fa-right-to-bracket"></i>
                </a>
                {% endif %}
            </button>
            {% if request.user.is_superuser %}
            <div class="form-buttons btn-nav">
                <a class="btn-small btn-secondary form-button" href="{% url 'update-parts-page' pk=partspage.pk %}"><i
                        class="fa-solid fa-user-pen"></i>
                </a>
                <a class="btn-small btn-secondary form-button" href="{% url 'delete-parts-page' pk=partspage.pk %}"><i
                        class="fa-solid fa-trash"></i>
                </a>
            </div>
            {% endif %}
        </div>
        <img src="{{partspage.imageurl}}" alt="image">
    </div>
    {% endfor %}
</section>
{% endblock content %}

spareparts/templates/spareparts/parts_form.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<h2 class="form-heading text-center">
    {% if request.resolver_match.url_name == 'create-warranty' %}
    Warranty Claim Form <div class="bottom-line"></div>
    {% elif request.resolver_match.url_name == 'update-warranty' %}
    Warranty Claim Form <div class="bottom-line"></div>

    {% else %}
    Form <div class="bottom-line"></div>
    {% endif %}
</h2>
<p class="form-lead text-center">Fill out the form field(s) below:</p>

<section id="form">
    <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
        </ul>
        {% endif %}
        {% for field in form %}
        <div class="input">
            <h1>{{field.label}}:</h1>
            <p>{{field}}</p>
        </div>
        {% endfor %}
        <div id="form-container">
            {{formset.management_form}}
            {% for field in formset %}
            <div class="input">
                <h1>Parts Required:</h1>
                <p>{{field}}</p>
            </div>
        </div>
        <div id="empty-form" class="input" style="display: none;">
            <p>{{formset.empty_form}}</p>
        </div>
        {% endfor %}
        <button class="btn btn-primary" id="add-more" type="button">Add More</button>
        <input class="submit btn btn-primary" type="submit"></input>
    </form>
</section>

<script src="{% static 'js/warranty.js' %}"></script>

{% endblock content %}

spareparts/templates/spareparts/reg_single.html
{% extends 'main.html' %}

{% block content %}

<section id="warranty-machine-single">
    <h2 class="text-center">Machine Registration Form <div class="bottom-line"></div>
    </h2>
    <button class="btn-nav form-buttons">
        <a href="{% url 'generate-reg' regsingle.id %}" class="btn btn-primary">Download PDF</a>
    </button>
    <div class="single-grid">
        <h1>Dealer Name: </h1>
        <p>{{regsingle.dealer_name}}</p>
        <h1>Dealer Address: </h1>
        <p>{{regsingle.dealer_address}}</p>
        <h1>Owner Name: </h1>
        <p>{{regsingle.owner_name}}</p>
        <h1>Owner Address: </h1>
        <p>{{regsingle.owner_address}}</p>
        <h1>Machine Model: </h1>
        <p>{{regsingle.machine_model}}</p>
        <h1>Serial Number: </h1>
        <p>{{regsingle.serial_number}}</p>
        <h1>Install Date: </h1>
        <p>{{regsingle.install_date}}</p>
        <h1>Invoice Number: </h1>
        <p>{{regsingle.invoice_number}}</p>
        <h1>Complete Supply: {{regsingle.complete_supply}}</h1>
        <p>{{regsingle.complete_supply}}</p>
        <h1>PDI Complete: </h1>
        <p>{{regsingle.pdi_complete}}</p>
        <h1>PTO Correct: </h1>
        <p>{{regsingle.pto_correct}}</p>
        <h1>Machine Test Run:</h1>
        <p>{{regsingle.machine_test_run}}</p>
        <h1>Safety Induction:</h1>
        <p>{{regsingle.safety_induction}}</p>
        <h1>Operator Handbook: </h1>
        <p>{{regsingle.operator_handbook}}</p>
        <h1>Date: </h1>
        <p>{{regsingle.date}}</p>
        <h1>Completed By: </h1>
        <p>{{regsingle.completed_by}}</p>
    </div>
    {% if request.user.is_superuser %}
    <div class="form-buttons btn-nav">
        <a class="btn-small btn-secondary form-button" href="{% url 'update-registration' pk=regsingle.pk %}"><i
                class="fa-solid fa-user-pen"></i>
        </a>
        <a class="btn-small btn-secondary form-button" href="{% url 'delete-registration' pk=regsingle.pk %}"><i
                class="fa-solid fa-trash"></i>
        </a>
    </div>
    {% endif %}
</section>

{% endblock content %}

spareparts/templates/spareparts/spare-parts.html
{% extends 'main.html' %}

{% block content %}


<section id="supplier-parts">
    <div class="container">
        <h2 class="section-title">
            Spare-Parts: Brand Selection<div class="bottom-line"></div>
        </h2>

        {% if request.user.is_superuser %}
        <button class="btn-nav">
            <a class="btn btn-secondary" href="{% url 'create-supplier-page' %}">Create Supplier
                <i class="fa-sharp fa-solid fa-right-to-bracket"></i></a>
        </button>
        {% endif %}

        {% if request.user.is_authenticated %}
        <button class="btn-nav form-buttons">
            <a id="warranty" class="btn btn-primary form-button" href="{% url 'create-warranty' %}">Warranty
                Form <i class="fa-sharp fa-solid fa-right-to-bracket"></i></a>
            <a id="registration" class="btn btn-primary form-button" href="{% url 'create-registration' %}">Register
                Machine <i class="fa-sharp fa-solid fa-right-to-bracket"></i></a>
        </button>
        {% endif %}

        <div class="index">
            <h1 class="index-heading">Index:
                <div class="bottom-line-side"></div>
            </h1>
            {% for spareparts in spareparts %}
            <h1 class="index-name"><a class="index-link" href="#supplier-parts-{{forloop.counter}}">{{forloop.counter}}
                    . {{spareparts.name}}</a></h1>
            {% endfor %}
        </div>

        <div class="supplier-parts-grid">
            {% for spareparts in spareparts %}
            <div class="supplier-parts-items" id="supplier-parts-{{forloop.counter}}">
                <h1>{{spareparts.name}} <div class="bottom-line"></div>
                </h1>
                <img src="{{spareparts.logo_image.url}}" alt="">
                <button class="btn-nav">
                    <a href="{% url 'parts-page' pk=spareparts.pk %}" class="btn btn-primary">Spare-Parts
                        <i class="fa-sharp fa-solid fa-right-to-bracket"></i>
                    </a>
                </button>
                {% if request.user.is_superuser %}
                <div class="form-buttons btn-nav">
                    <a class="btn-small btn-secondary form-button"
                        href="{% url 'update-supplier-page' pk=spareparts.pk %}"><i class="fa-solid fa-user-pen"></i>
                    </a>
                    <a class="btn-small btn-secondary form-button"
                        href="{% url 'delete-supplier-page' pk=spareparts.pk %}"><i class="fa-solid fa-trash"></i>
                    </a>
                </div>
                {% endif %}
            </div>
            {% endfor %}
        </div>

    </div>
</section>

{% endblock content %}

spareparts/templates/spareparts/warranty_claims.html
{% extends 'main.html' %}

{% block content %}


<section id="warranty-machine">
    <div class="index">
        <h1 class="index-heading">Index:
            <div class="bottom-line-side"></div>
        </h1>
        {% for warranty in warranty %}
        <h1 class="index-name"><a class="index-link" href="#form-warranty-{{forloop.counter}}">{{forloop.counter}}
                . {{warranty.owner_name}}</a></h1>
        {% endfor %}
    </div>

    {% for warranty in warranty %}
    <div class="warranty-machine-grid" id="form-warranty-{{forloop.counter}}">
        <h1>{{forloop.counter}} . {{warranty.owner_name}} -- {{warranty.dealer}}</h1>
        <button class="btn-nav form-button">
            <a class="btn-small btn-primary" href="{% url 'single-warranty' pk=warranty.pk %}">View Form
                <i class="fa-sharp fa-solid fa-right-to-bracket"></i></a>
        </button>
    </div>
    {% endfor %}
</section>

{% endblock content %}