blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('blogs/', views.blogs, name='blogs'),
    path('blog/<str:pk>/', views.blog, name='blog'),

    path('exhibitions/', views.exhibitions, name='exhibitions'),

    path('create-blog/', views.createBlog, name='create-blog'),
    path('update-blog/<str:pk>/', views.updateBlog, name='update-blog'),
    path('delete-blog/<str:pk>/', views.deleteBlog, name='delete-blog'),

    path('create-exhibition/', views.createExhibition, name='create-exhibition'),
    path('update-exhibition/<str:pk>/', views.updateExhibition, name='update-exhibition'),
    path('delete-exhibition/<str:pk>/', views.deleteExhibition, name='delete-exhibition'),
]

farmec/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.home, name='home'),

    path('admin/', admin.site.urls),

    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),

    path('home/', include('home.urls')),
    path('about/', include('about.urls')),
    path('suppliers/', include('suppliers.urls')),
    path('blog/', include('blog.urls')),
    path('spareparts/', include('spareparts.urls')),
    path('stripepayments/', include('stripepayments.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

suppliers/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('suppliers/', views.suppliers, name='suppliers'),
    path('supplier/<str:pk>/', views.supplier, name='supplier'),
    path('machine/<str:pk>/', views.machine, name='machine'),

    path('create-supplier/', views.createSupplier, name='create-supplier'),
    path('update-supplier/<str:pk>/', views.updateSupplier, name='update-supplier'),
    path('delete-supplier/<str:pk>/', views.deleteSupplier, name='delete-supplier'),

    path('create-machine/<str:pk>/', views.createMachine, name='create-machine'),
    path('update-machine/<str:pk>/', views.updateMachine, name='update-machine'),
    path('delete-machine/<str:pk>/', views.deleteMachine, name='delete-machine'),

    path('create-product/<str:pk>/', views.createProduct, name='create-product'),
    path('update-product/<str:pk>/', views.updateProduct, name='update-product'),
    path('delete-product/<str:pk>/', views.deleteProduct, name='delete-product'),
]

suppliers/models.py
from django.db import models
import uuid

# Create your models here.
class Supplier(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    logo_image = models.ImageField(null=True, blank=True, upload_to='models/', default="default.jpg")
    marketing_image = models.ImageField(null=True, blank=True, upload_to='models/', default="default.jpg")
    description = models.TextField(blank=True, null=True)
    short_description = models.TextField(blank=True, null=True)
    social_facebook = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_instagram = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ['created']

    @property
    def imageurl(self):
        try:
            url = self.logo_image.url
        except: 
            url = ''
        return url

    @property
    def marketing_imageurl(self):
        try:
            url = self.marketing_image.url
        except: 
            url = ''
        return url

class Machine(models.Model):
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    machine_image = models.ImageField(null=True, blank=True, upload_to='models/', default="default.jpg")
    description = models.TextField(blank=True, null=True)
    short_description = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    class Meta:
        ordering = ['created']
    
    def __str__(self):
        return str(self.name)

    @property
    def imageurl(self):
        try:
            url = self.machine_image.url
        except: 
            url = ''
        return url

class Product(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    product_image = models.ImageField(null=True, blank=True, upload_to='models/', default="default.jpg")
    description = models.TextField(blank=True, null=True)
    short_description = models.CharField(max_length=200, blank=True, null=True)
    serial_number = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return str(self.name)

    @property
    def imageurl(self):
        try:
            url = self.product_image.url
        except: 
            url = ''
        return url

class Fact(models.Model):
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, 
                            primary_key=True, editable=False)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return str(self.description)

suppliers/forms.py
from django.db.models.base import Model
from django.forms import ModelForm, widgets
from django import forms
from . models import Supplier, Machine, Product

class SupplierForm(ModelForm):
    class Meta:
        model = Supplier
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(SupplierForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})
    
class MachineForm(ModelForm):
    class Meta:
        model = Machine
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(MachineForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

suppliers/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from . models import Supplier, Machine, Product
from . forms import SupplierForm, MachineForm, ProductForm
from spareparts.models import SupplierPage

# Create your views here.
def suppliers(request):

    context = {}
    return render(request, 'suppliers/suppliers.html', context)

def supplier(request, pk):
    supplier = Supplier.objects.get(id=pk)

    context = {'supplier': supplier}
    return render(request, 'suppliers/supplier.html', context)

def machine(request, pk):
    machine = Machine.objects.get(id=pk)

    context = {'machine': machine, }
    return render(request, 'suppliers/machine.html', context)

# Supplier Model CRUD:
@login_required(login_url='login')
def createSupplier(request): 
    form = SupplierForm()

    if request.user.is_superuser:
        if request.method == 'POST':
            form = SupplierForm(request.POST, request.FILES)
            if form.is_valid():
                post = form.save(commit=False)
                post.owner = suppliers
                post.save()
            return redirect('suppliers')

    context = {'form': form}
    return render(request, 'suppliers/supplier_form.html', context)

@login_required(login_url='login')
def updateSupplier(request, pk):
    supplier = Supplier.objects.get(id=pk)
    form = SupplierForm(instance=supplier)
    
    if request.method == 'POST':

        form = SupplierForm(request.POST, request.FILES, instance=supplier)
        if form.is_valid():
            supplier = form.save()

        return redirect('supplier', pk=pk)
 
    context = {'form': form, 'supplier':supplier}
    return render(request, 'suppliers/supplier_form.html', context)

@login_required(login_url='login')
def deleteSupplier(request, pk):
    supplier = Supplier.objects.get(id=pk)
    
    if request.method == 'POST':
        supplier.delete()
        return redirect('suppliers')
 
    context = {'object': supplier}
    return render(request, 'delete_form.html', context)

# Machine Model CRUD:
@login_required(login_url='login')
def createMachine(request, pk): 
    machines = Machine.objects.all()
    supplier = Supplier.objects.get(id=pk)
    form = MachineForm()

    if request.user.is_superuser:
        if request.method == 'POST':
            form = MachineForm(request.POST, request.FILES)
            if form.is_valid():
                post = form.save(commit=False)
                post.owner = machines
                post.save()
            return redirect('supplier', pk=pk)

    context = {'form': form, 'machines': machines, 'supplier': supplier}
    return render(request, 'suppliers/supplier_form.html', context)

@login_required(login_url='login')
def updateMachine(request, pk):
    machines = Machine.objects.all()
    machine = Machine.objects.get(id=pk)
    form = MachineForm(instance=machine)
    
    if request.method == 'POST':

        form = MachineForm(request.POST, request.FILES, instance=machine)
        if form.is_valid():
            machine = form.save()
        return redirect('supplier', pk=machine.supplier.pk)
 
    context = {'form': form, 'machines': machines, 'machine': machine}
    return render(request, 'suppliers/supplier_form.html', context)

@login_required(login_url='login')
def deleteMachine(request, pk):
    machine = Machine.objects.get(id=pk)
    
    if request.method == 'POST':
        machine.delete()
        return redirect('supplier', pk=machine.supplier.pk)
 
    context = {'object': machine}
    return render(request, 'delete_form.html', context)

# Product Model CRUD:
@login_required(login_url='login')
def createProduct(request, pk): 
    products = Product.objects.all()
    machine = Machine.objects.get(id=pk)
    form = ProductForm()

    if request.user.is_superuser:
        if request.method == 'POST':
            form = ProductForm(request.POST, request.FILES)
            if form.is_valid():
                post = form.save(commit=False)
                post.owner = products
                post.save()
            return redirect('machine', pk=pk)

    context = {'form': form, 'products': products}
    return render(request, 'suppliers/supplier_form.html', context)

@login_required(login_url='login')
def updateProduct(request, pk):
    products = Product.objects.all()
    product = Product.objects.get(id=pk)
    form = ProductForm(instance=product)
    
    if request.method == 'POST':

        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            products = form.save()

        return redirect('machine', pk=product.machine.pk)
 
    context = {'form': form, 'products': products, 'product': product}
    return render(request, 'suppliers/supplier_form.html', context)

@login_required(login_url='login')
def deleteProduct(request, pk):
    product = Product.objects.get(id=pk)
    
    if request.method == 'POST':
        product.delete()
        return redirect('machine', pk=product.machine.pk)
 
    context = {'object': product}
    return render(request, 'delete_form.html', context)

suppliers/templates/suppliers/machine.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<section id="products" class="products">
    <div class="container">
        <div class="product-index">
            <h5>Product Index <div class="bottom-line-side"></div>
            </h5>
            {% for product in machine.product_set.all %}
            <h1><a href="#product-{{forloop.counter}}">{{forloop.counter}} - {{product.name}}</a>
            </h1>
            {% endfor %}
        </div>

        {% for product in machine.product_set.all %}
        <div class="product-grid" id="product-{{forloop.counter}}">
            <h1>
                {{product.name}} <div class="bottom-line-small"></div>
            </h1>
            <img src="{{product.imageurl}}" alt="product image">
            <p>{{product.description}}</p>

            {% if request.user.is_superuser %}
            <div class="form-buttons btn-nav">
                <a class="btn-small btn-secondary form-button" href="{% url 'update-product' pk=product.pk %}"><i
                        class="fa-solid fa-user-pen"></i>
                </a>
                <a class="btn-small btn-secondary form-button" href="{% url 'delete-product' pk=product.pk %}"><i
                        class="fa-solid fa-trash"></i>
                </a>
            </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    {% if request.user.is_superuser %}
    <button class="form-buttons btn-nav btn-create">
        <a class="btn-small btn-primary form-buttom" href="{% url 'create-product' pk=machine.pk %}">Create Product <i
                class="fa-sharp fa-solid fa-right-to-bracket"></i></a>
    </button>
    {% endif %}
</section>

{% endblock content %}

suppliers/templates/suppliers/supplier.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<section id="profile">
    <div class="container">
        <div class="profile-body">
            <div class="profile-header">
                <h1 class="text-center">{{supplier.name}}
                    <div class="bottom-line"></div>
                </h1>
                <div class="link-grid">
                    <div class="supplier-social">
                        {% if supplier.social_facebook %}
                        <a href="{{supplier.social_facebook}}" target="_blank"><button class="facebook"><i
                                    class="fab fa-facebook"></i></button></a>
                        {% endif %}
                        {% if supplier.social_twitter %}
                        <a href="{{supplier.social_twitter}}" target="_blank"><button class="twitter"><i
                                    class="fab fa-twitter"></i></button></a>
                        {% endif %}
                        {% if supplier.social_instagram %}
                        <a href="{{supplier.social_instagram}}" target="_blank"><button class="instagram"><i
                                    class="fab fa-instagram"></i></button></a>
                        {% endif %}
                        {% if supplier.social_youtube %}
                        <a href="{{supplier.social_youtube}}" target="_blank"><button class="youtube"><i
                                    class="fab fa-youtube"></i></button></a>
                        {% endif %}
                        {% if supplier.social_linkedin %}
                        <a href="{{supplier.social_linkedin}}" target="_blank"><button class="linkedin"><i
                                    class="fab fa-linkedin"></i></button></a>
                        {% endif %}
                        {% if supplier.social_website %}
                        <a href="{{supplier.social_website}}" target="_blank"><button class="website"><i
                                    class="fa-solid fa-globe"></i></button></a>
                        {% endif %}
                    </div>

                </div>
                <div class="border">
                    <div class="profile-grid-description" id="description">
                        <div class="logo-index">
                            <img class="profile-logo" src="{{supplier.imageurl}}" alt="logo">
                            <div class="model-index">
                                <h1>Machinery Index:
                                    <div class="bottom-line"></div>
                                </h1>
                                {% for machine in supplier.machine_set.all %}
                                <h1><a href="#machines-{{forloop.counter}}">{{forloop.counter}} .
                                        {{machine.name}}</a></h1>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="bottom-line-side"></div>
                        <p>{{supplier.description}}</p>
                    </div>
                    <div class="profile-facts">
                        <h1>{{supplier.name.split.0}} Features:</h1>
                        <div class="bottom-line-side"></div>
                        {% for fact in supplier.fact_set.all %}
                        <p>{{fact}}</p>
                        {% endfor %}
                    </div>

                    {% if request.user.is_superuser %}
                    <div class="form-buttons btn-nav">
                        <a class="btn-small btn-secondary form-button"
                            href="{% url 'update-supplier' pk=supplier.pk %}"><i class="fa-solid fa-user-pen"></i>
                        </a>
                        <a class="btn-small btn-secondary form-button"
                            href="{% url 'delete-supplier' pk=supplier.pk %}"><i class="fa-solid fa-trash"></i>
                        </a>
                    </div>
                    {% endif %}
                    <div class="nav-button">
                        <a href="#cards" class="btn btn-primary">
                            Brand Products <i class="fa-sharp fa-solid fa-circle-chevron-down"></i>
                        </a>
                    </div>
                </div>
            </div>

            <div class="cards" id="cards">
                {% for machine in supplier.machine_set.all %}
                <div class="machines" id="machines-{{ forloop.counter }}">
                    <div class="machine-card">
                        <img src="{{machine.imageurl}}" alt="machine-image">
                        <div class="machine-info">
                            <h1>{{machine.name}}</h1>
                            <div class="bottom-line-side"></div>
                            <p>{{machine.description}}</p>
                            <a href="{% url 'machine' pk=machine.pk %}" class="btn btn-primary">
                                View Products
                                <i class="fa-sharp fa-solid fa-right-to-bracket"></i>
                            </a>
                            {% if request.user.is_superuser %}
                            <div class="form-buttons btn-nav">
                                <a class="btn-small btn-secondary form-button"
                                    href="{% url 'update-machine' pk=machine.pk %}"><i class="fa-solid fa-user-pen"></i>
                                </a>
                                <a class="btn-small btn-secondary form-button"
                                    href="{% url 'delete-machine' pk=machine.pk %}"><i class="fa-solid fa-trash"></i>
                                </a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
        {% if request.user.is_superuser %}
        <button class="btn-nav form-buttons">
            <a class="btn btn-primary form-button" href="{% url 'create-machine' pk=supplier.pk %}">Create Machine
                <i class="fa-sharp fa-solid fa-right-to-bracket"></i></a>
        </button>
        {% endif %}
    </div>
</section>

{% endblock content %}

suppliers/templates/suppliers/supplier_form.html
{% extends 'main.html' %}

{% block content %}
<h2 class="form-heading text-center">
    {% if request.resolver_match.url_name == 'create-supplier' %}
    Supplier Form <div class="bottom-line"></div>
    {% elif request.resolver_match.url_name == 'update-supplier' %}
    Supplier Form <div class="bottom-line"></div>

    {% elif request.resolver_match.url_name == 'create-machine' %}
    Machine Form <div class="bottom-line"></div>
    {% elif request.resolver_match.url_name == 'update-machine' %}
    Machine Form <div class="bottom-line"></div>

    {% elif request.resolver_match.url_name == 'create-product' %}
    Product From <div class="bottom-line"></div>
    {% elif request.resolver_match.url_name == 'update-product' %}
    Product Form <div class="bottom-line"></div>

    {% else %}
    Form <div class="bottom-line"></div>
    {% endif %}
</h2>
<p class="form-lead text-center">Fill out the form field(s) below:</p>

<section id="form">
    <form class="form" method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div class="input">
            <h1>{{field.label}}:</h1>
            <p>{{field}}</p>
        </div>
        {% endfor %}
        <input class="submit btn btn-primary" type="submit"></input>
    </form>
</section>

{% endblock content %}

suppliers/templates/suppliers/suppliers.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<section id="suppliers">
    <div class="container">

        <div class="index">
            <h1 class="index-heading">Index:
                <div class="bottom-line-side"></div>
            </h1>
            {% for supplier in suppliers %}
            <h1 class="index-name"><a class="index-link"
                    href="#supplier-profile-{{forloop.counter}}">{{forloop.counter}} . {{supplier.name}}</a></h1>
            {% endfor %}
        </div>

        {% for supplier in suppliers %}
        <div class="supplier-profile" id="supplier-profile-{{ forloop.counter }}">
            <div class="supplier-info">
                <img src="{{supplier.imageurl}}" alt="supplier-logo">
                <h1>{{supplier.name}}</h1>
                <div class="link-grid">
                    <div class="supplier-social">
                        {% if supplier.social_facebook %}
                        <a href="{{supplier.social_facebook}}" target="_blank"><button class="facebook"><i
                                    class="fab fa-facebook"></i></button></a>
                        {% endif %}
                        {% if supplier.social_twitter %}
                        <a href="{{supplier.social_twitter}}" target="_blank"><button class="twitter"><i
                                    class="fab fa-twitter"></i></button></a>
                        {% endif %}
                        {% if supplier.social_instagram %}
                        <a href="{{supplier.social_instagram}}" target="_blank"><button class="instagram"><i
                                    class="fab fa-instagram"></i></button></a>
                        {% endif %}
                        {% if supplier.social_youtube %}
                        <a href="{{supplier.social_youtube}}" target="_blank"><button class="youtube"><i
                                    class="fab fa-youtube"></i></button></a>
                        {% endif %}
                        {% if supplier.social_linkedin %}
                        <a href="{{supplier.social_linkedin}}" target="_blank"><button class="linkedin"><i
                                    class="fab fa-linkedin"></i></button></a>
                        {% endif %}
                        {% if supplier.social_website %}
                        <a href="{{supplier.social_website}}" target="_blank"><button class="website"><i
                                    class="fa-solid fa-globe"></i></button></a>
                        {% endif %}
                    </div>
                    <button class="supplier-link">
                        <a href="{% url 'supplier' pk=supplier.pk %}" class="btn btn-secondary">
                            Learn More
                            <i class="fa-sharp fa-solid fa-right-to-bracket"></i>
                        </a>
                    </button>
                </div>
            </div>
            <img src="{{supplier.marketing_imageurl}}" alt="marketing-image" class="marketing-image">
            <div class="supplier-description">
                <p>{{supplier.description|linebreaks}}</p>
            </div>

            <div class="supplier-facts">
                {% for fact in supplier.fact_set.all %}
                <p>{{fact}}</p>
                <br>
                {% endfor %}
            </div>
        </div>
        {% endfor %}

        {% if request.user.is_superuser %}
        <button class="btn-nav">
            <a class="btn btn-primary form-buttom" href="{% url 'create-supplier' %}">Create Supplier <i
                    class="fa-sharp fa-solid fa-right-to-bracket"></i></a>
        </button>
        {% endif %}
    </div>
</section>

{% endblock content %}